"""
Project Euler solutions: problem26 through problem50.

Problems26To50Mixin is combined into EulerSolver in solver.py. It
genuinely inherits from UtilsMixin and EasterEggsMixin (which itself
inherits HelpersMixin) since these problems call self.header,
self.run_task, self.is_prime, self._try_easter_egg, and so on - real
inheritance is what lets Pylance/Pyright resolve those calls.
"""

import math
import itertools
import collections

from colorama import Fore

from .utils import UtilsMixin
from .easter_eggs import EasterEggs


class Problems26To50(UtilsMixin, EasterEggs):
    """Problem solutions 26-50."""

    def problem26(self):
        "Find the value of d < 1000 for which 1/d contains the longest recurring cycle in its decimal fraction part."
        self.header(
            26,
            "Find the value of d < 1000 for which 1/d contains the longest recurring cycle in its decimal fraction part."
        )
        def get_cycle_length(d):
            # Track the step/index at which each remainder was seen
            seen_remainders = {}
            remainder = 1
            step = 0
            while remainder != 0:
                if remainder in seen_remainders:
                    return step - seen_remainders[remainder]
                
                seen_remainders[remainder] = step
                remainder = (remainder * 10) % d
                step += 1
            return 0  # Divides evenly 
        
        def task():
            max_len = 0
            best_d = 0
            for d in range(2, 1000):
                length = get_cycle_length(d)
                if length > max_len:
                    max_len = length
                    best_d = d
            return best_d, max_len
        
        d_value, cycle_len = self.run_task(
            "Finding the largest recurring decimal...",
            task       
        )
        print(f"The value of d < 1000 with the longest cycle is: {Fore.GREEN}{d_value}{Fore.RESET}")
        print(f"Length of the cycle is: {Fore.GREEN}{cycle_len}{Fore.RESET}")
    
    def problem27(self):
        "Find the product of the coefficients a and b in the quadratic expression n^2 + an + b that yields the maximum number of consecutive primes, starting with n = 0"
        self.header(
            27,
            "Find the product of the coefficients a and b in the quadratic expression n^2 + an + b that yields the maximum number of consecutive primes, starting with n = 0"
        )
        def task():
            max_primes = 0
            best_a = 0
            best_b = 0
            for b in range(2, 1000):
                if not self.is_prime(b):
                    continue
                for a in range(-999, 1000):
                    n = 0
                    while True:
                        candidate = n**2 + a * n + b
                        if candidate <= 0 or not self.is_prime(candidate):
                            break
                        n += 1
                    if n > max_primes:
                        max_primes = n
                        best_a = a
                        best_b = b
            return best_a * best_b, best_a, best_b
        
        product, a, b = self.run_task(
            "Finding the coefficents and the product of the former...",
            task
        )
        print(f"The coefficients are: a = {Fore.GREEN}{a}{Fore.RESET}, b = {Fore.GREEN}{b}{Fore.RESET}")
        print(f"Product of coefficients (a * b) is: {Fore.GREEN}{product}{Fore.RESET}")

    def problem28(self):
        "Find the sum of the numbers on the diagonals in a 1001 by 1001 spiral"
        self.header(
            28,
            "Find the sum of the numbers on the diagonals in a 1001 by 1001 spiral"
        )
        def task(grid_size):
            total_sum = 1
            current_number = 1
            
            # Outer layers advance by 2 step sizes each time (2, 4, 6, ..., grid_size - 1)
            for step in range(2, grid_size, 2):
                for _ in range(4):
                    current_number += step
                    total_sum += current_number
                    
            return total_sum
        
        result = self.run_task(
            "Finding the sum...",
            task,
            1001
        )
        print(f"The sum of numbers on the diagonals is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem29(self):
        "Find the number of distinct terms in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100"
        self.header(
            29,
            "Find the number of distinct terms in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100"
        )
        def task():
            # Use a set comprehension to automatically filter out duplicate values
            distinct_powers = {a**b for a in range(2, 101) for b in range(2, 101)}
            return len(distinct_powers)
        
        result = self.run_task(
            "Finding the number of distinct terms",
            task
        )
        print(f"The number of distict terms is: {Fore.GREEN}{result}{Fore.RESET}")
    
    def problem30(self):
        "Find the sum of all the numbers that can be written as the sum of fifth powers of their digits."
        self.header(
            30,
            "Find the sum of all the numbers that can be written as the sum of fifth powers of their digits."
        )
        def task():
            total_sum = 0
            upper_bound = 6 * (9 ** 5)
            for number in range(2, upper_bound + 1):
                digit_sum = sum(int(digit) ** 5 for digit in str(number))
                if digit_sum == number:
                    total_sum += number    
            return total_sum
        
        result = self.run_task(
            "Finding the sum...",
            task
        )
        print(f"The sum of all the numbers that can be written as the sum of fifth powers of there digits is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem31(self):
        "Find the number of different ways can £2 be made using any number of coins?"
        self.header(
            31,
            "Find the number of different ways can £2 be made using any number of coins?"
        )
        def task():
            target = 200
            coins = [1, 2, 5, 10, 20, 50, 100, 200]
            
            # dp[i] will store the number of ways to form a target sum 'i'
            dp = [1] + [0] * target
            
            for coin in coins:
                for i in range(coin, target + 1):
                    dp[i] += dp[i - coin]
                    
            return dp[target]
        
        result = self.run_task(
            "Finding all the ways to make £2...",
            task
        )
        print(f"The total number of ways to make £2 is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem32(self):
        "Find the sum of all products whose multiplicand/multiplier/product identity can be written as a 1 through 9 pandigital."
        self.header(
            32,
            "Find the sum of all products whose multiplicand/multiplier/product identity can be written as a 1 through 9 pandigital."
        )
        def task():
             # Store unique products to avoid counting duplicates
            unique_products = set()
            for product in range(1000, 10000):
                if self.has_pandigital_product(product):
                    unique_products.add(product)
            return sum(unique_products)

        result = self.run_task(
            "Finding the sum of the pandigital...",
            task
        )
        print(f"The sum of all products whose identities can be written as a 1 - 9 pandigital is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem33(self):
        "Find the value of the denominator. If the product of these four fractions is given in its lowest common terms."
        self.header(
            33,
            "Find the value of the denominator. If the product of these four fractions is given in its lowest common terms."
        )
        def task():
            product_numerator = 1
            product_denominator = 1
            for d in range(10, 100):
                for n in range(10, d):
                    n1, n0 = n // 10, n % 10
                    d1, d0 = d // 10, d % 10
                    if n0 == 0 and d0 == 0:
                        continue
                    if n0 == d1 and (n * d0 == d * n1):
                        product_numerator *= n
                        product_denominator *= d
            final_denominator = product_denominator // math.gcd(product_numerator, product_denominator)
            return final_denominator
        result = self.run_task(
            "Finding the denominator...",
            task
        )
        print(f"The value of the denominator when the product of these four factions is given in its lowest common terms is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem34(self):
        "Find the sum of all numbers which are equal to the sum of the factorial of their digits."
        self.header(
            34,
            "Find the sum of all numbers which are equal to the sum of the factorial of their digits."
        )
        def task():
            factorials = [math.factorial(i) for i in range(10)]
            def sum_of_digit_factorials(n):
                total = 0
                while n > 0:
                    total += factorials[n % 10]
                    n //= 10
                return total
            upper_limit = 7 * factorials[9]
            match_sum = 0
            for num in range(3, upper_limit + 1):
                if num == sum_of_digit_factorials(num):
                    match_sum += num
            return match_sum
        result = self.run_task(
            "Finding the sum...",
            task
        )
        print(f"The sum of all number that are equal to the sum of the factorial of their digits is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem35(self):
        "Find the number of circular primes are there below one million."
        self.header(
            35,
            "Find the number of circular primes are there below one million."
        )
        def task():
            limit = 1_000_000
            is_prime_lookup = self.sieve_of_eratosthenes_list(limit)
            circular_prime_count = 0
            invalid_digits = {'0', '2', '4', '5', '6', '8'}
            for num in range(2, limit):
                if not is_prime_lookup[num]:
                    continue
                num_str = str(num)
                if len(num_str) > 1 and any(digit in invalid_digits for digit in num_str):
                    continue
                is_circular = True
                for i in range(len(num_str)):
                    rotation = int(num_str[i:] + num_str[:i])
                    if not is_prime_lookup[rotation]:
                        is_circular = False
                        break
                if is_circular:
                    circular_prime_count += 1    
            return circular_prime_count

        result = self.run_task(
            "Finding all circular primes under 1000000...",
            task
        )
        print(f"The number of circulat primes under one million is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem36(self):
        "Find the sum of all numbers, less than one million, which are palindromic in base 10 and base 2."
        self.header(
            36,
            "Find the sum of all numbers, less than one million, which are palindromic in base 10 and base 2."
        )
        def task():
            total_sum = 0
            # Even numbers in binary always end in 0, so they cannot be base-2 palindromes (no leading zeros).
            # Thus, we only check odd numbers.
            for n in range(1, 1000000, 2):
                if self.is_palindrome(str(n)) and self.is_palindrome(bin(n)[2:]):
                    total_sum += n
            return total_sum
        result = self.run_task(
            "Finding the sum of all palindromic numbers...",
            task
        )
        print(f"The sum of all numbers, less than one million, which are palindromic in base 10 and base 2 is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem37(self):
        "Find the sum of the only eleven primes that are both truncatable from left to right and right to left."
        self.header(
            37,
            "Find the sum of the only eleven primes that are both truncatable from left to right and right to left."
        )
        """
        if self._try_easter_egg(37):
                    return
        """
        def task():
            limit = 1000000
            is_prime = self.sieve_of_eratosthenes_list(limit)

            def is_truncatable(n: int) -> bool:
                # Single-digit primes are excluded by problem definition
                if n < 10:
                    return False
                str_n = str(n)
                for i in range(1, len(str_n)):
                    if not is_prime[int(str_n[:i])] or not is_prime[int(str_n[i:])]:
                        return False
                return True
            truncatable_primes = []
            current_number = 11
            while len(truncatable_primes) < 11:
                if is_prime[current_number] and is_truncatable(current_number):
                    truncatable_primes.append(current_number)
                current_number += 2  # Skip even numbers to save time

            return sum(truncatable_primes)
        result = self.run_task(
            "Finding all truncateable primes...",
            task
        )
        print(f"The sum of the only eleven primes that are truncatable from left to right and right to left is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem38(self):
        "Find the largest 1 to 9 pandigital 9-digit number that can be formed as the concatenated product of an integer with (1, 2,...,n) where n > 1."
        self.header(
            38,
            "Find the largest 1 to 9 pandigital 9-digit number that can be formed as the concatenated product of an integer with (1, 2,...,n) where n > 1."
        )
        def task():
            for num in range(9876, 9122, -1):
                concatenated = str(num) + str(2 * num)
                if len(set(concatenated)) == 9 and '0' not in concatenated:
                    return concatenated
        result = self.run_task(
            "Finding the number...",
            task
        )
        print(f"The largest 1 to 9 pandigital 9-digit number is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem39(self):
        "Find the perimeter that maximizes the number of integer right-angled triangle solutions for p ≤ 1000"
        self.header(
            39,
            "Find the perimeter that maximizes the number of integer right-angled triangle solutions for p ≤ 1000"
        )
        if self._try_easter_egg(39):
            return
        def task(max_p=1000):
            perimeters = []
            for a in range(1, max_p // 3):
                for b in range(a, max_p // 2):
                    c_squared = a**2 + b**2
                    c = int(c_squared**0.5)
                    if c**2 == c_squared:
                        p = a + b + c
                        if p <= max_p:
                            perimeters.append(p)
            frequency_map = collections.Counter(perimeters)
            most_common_p, max_solutions = frequency_map.most_common(1)[0]
            return most_common_p, max_solutions
        result, _max = self.run_task(
            "FInding the perimeter...",
            task
        )
        print(f"The perimeter that maximizes the number of integer right-angled triangle solutions is: {Fore.GREEN}{result}{Fore.RESET}")
        print(f"The max solutions it gives is: {Fore.GREEN}{_max}{Fore.RESET}")

    def problem40(self):
        "Find the product of specific positional digits in Champernowne's constant."
        self.header(
            40,
            "Find the product of specific positional digits in Champernowne's constant."
        )
        def task():
            champernowne_str = ""
            i = 1
            while len(champernowne_str) < 1000000:
                champernowne_str += str(i)
                i += 1
            product = 1
            for power in range(7):
                target_index = 10**power
                digit = int(champernowne_str[target_index - 1])
                product *= digit
            return product

        result = self.run_task(
            "Combing through Champernowne's Constant...",
            task
        )
        print(f"The product in Champernowne's constant is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem41(self):
        "Find the largest n-digit pandigital prime that exists"
        self.header(
            41,
            "Find the largest n-digit pandigital prime that exists"
        )
        """
        if self._try_easter_egg(41):
            return
        """
        def task():
            # Start with 7 digits since 9 and 8 digit pandigitals are always divisible by 3
            digits = "7654321"
            for p in itertools.permutations(digits):
                num = int("".join(p))
                if self.is_prime(num):
                    return num
        result = self.run_task(
            "Finding the pandigital prime...",
            task
        )
        print(f"The largest pandigital prime that exists is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem42(self):
        "Find the number of triangle words in a text file."
        self.header(
            42,
            "Find the number of triangle words in a text file."
        )
        def task():
            with open("0042_words.txt", "r") as f:
                content = f.read()
            # Clean up and split the CSV-style quoted words
            words = content.strip('"').split('","')
            triangle_count = sum(1 for w in words if self.is_triangle(self.word_value(w)))
            return triangle_count
        result = self.run_task(
            "Finding the number of triangle words...",
            task
        )
        print(f"The number of triangle words in the text file is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem43(self):
        "Find the sum of all 0-to-9 pandigital numbers that have a specific sub-string divisibility property tested against the primes 2, 3, 5, 7, 11, 13, and 17"
        self.header(
            43,
            "Find the sum of all 0-to-9 pandigital numbers that have a specific sub-string divisibility property tested against the primes 2, 3, 5, 7, 11, 13, and 17"
        )
        def task():
            total_sum = 0
            # Generate all permutations of digits 0 through 9
            for p in itertools.permutations(range(10)):
                if p[0] == 0:
                    continue  # Not a valid 10-digit number if it starts with 0
                if self.is_substring_divisible(p):
                    number_val = int("".join(map(str, p)))
                    total_sum += number_val
            return total_sum
        result = self.run_task(
            "Finding the sum...",
            task
        )
        print(f"The sum of all 0-to-9 pandigital numbers that have a specific sub-string divisibility property tested against primes is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem44(self):
        "Find the pair of pentagonal numbers with a pentagonal sum and difference that minimizes their difference."
        self.header(
            44,
            "Find the pair of pentagonal numbers with a pentagonal sum and difference that minimizes their difference."
        )
        def task():
            pentagons = []
            k = 1
            while True:
                pk = k * (3 * k - 1) // 2
                pentagons.append(pk)
                for j in range(k - 1, -1, -1):
                    pj = pentagons[j]
                    if self.is_pentagonal(pk - pj) and self.is_pentagonal(pk + pj):
                        return pk, pj, pk - pj
                k += 1
        num1, num2, result = self.run_task(
            "Finding the pair of pentagonal numbers...",
            task
        )
        print(f"The pair of pentagonal numbers with a pentagonal sum and difference that minimizes their difference are: {Fore.GREEN}{num1}{Fore.RESET} and {Fore.GREEN}{num2}{Fore.RESET}")
        print(f"The difference of the numbers is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem45(self):
        "Find the next triangle number that is also pentagonal and hexagonal."
        self.header(
            45,
            "Find the next triangle number that is also pentagonal and hexagonal."
        )
        def task():
            n = 143
            while True:
                n += 1
                h = n * (2 * n - 1)
                # Check if h is pentagonal: (sqrt(24h + 1) + 1) / 6 must be an integer
                p_discriminant = (24 * h + 1) ** 0.5
                if p_discriminant.is_integer() and (p_discriminant + 1) % 6 == 0:
                    return h
        result = self.run_task(
            "Finding the triangle number that is also pentagonal and hexagonal...",
            task          
        )
        print(f"The next triangle number that is booth pentagonal and hexagonal is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem46(self):
        "Find the smallest odd composite that cannot be written as the sum of a prime and twice a square."
        self.header(
            46,
            "Find the smallest odd composite that cannot be written as the sum of a prime and twice a square."
        )
        def task():
            primes = [2]
            n = 3
            while True:
                if self.is_prime(n):
                    primes.append(n)
                else:
                    falsified = True
                    for p in primes:
                        if p >= n:
                            break
                        remainder = (n - p) // 2
                        root = math.isqrt(remainder)
                        if root * root == remainder:
                            falsified = False
                            break
                    if falsified:
                        return n
                n += 2 
        result = self.run_task(
            "Combing through odd numbers...",
            task
        )
        print(f"The smallest odd composite that satisfies the conditions is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem47(self):
        "Find the first four consecutive integers to have four distinct prime factors each."
        self.header(
            47,
            "Find the first four consecutive integers to have four distinct prime factors each."
        )
        def task(limit=200_000):
            counts = [0] * limit
            for i in range(2, limit):
                if counts[i] == 0:  # i is prime
                    for j in range(i, limit, i):
                        counts[j] += 1

            # Look for 4 consecutive numbers with 4 distinct prime factors
            for i in range(2, limit - 3):
                if (
                    counts[i] == 4
                    and counts[i + 1] == 4
                    and counts[i + 2] == 4
                    and counts[i + 3] == 4
                ):
                    return i, i+1, i+2, i+3
        num1, num2, num3, num4 = self.run_task(
            "Finding the first 4...",
            task
        )
        print(f"The first four consecutive integers to have four distinct prime factors each are: {Fore.GREEN}{num1}, {num2}, {num3}, {num4}{Fore.RESET}")
        print(f"With the first being: {Fore.GREEN}{num1}{Fore.RESET}")
        
    def problem48(self):
        "Find the last ten digits of the sum of self-powers from 1 to 1000."
        self.header(
            48,
            "Calculate the last ten digits of the sum of self-powers from 1 to 1000."
        )
        def task():
            # Define the modulus for the last 10 digits
            MOD = 10**10
            total_sum = sum(pow(i, i, MOD) for i in range(1, 1001))
            result = total_sum % MOD
            return result
        result = self.run_task(
            "Calculating a huge number...",
            task
        )
        print(f"The last ten digits of the sum of self-powers is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem49(self):
        "Find the second 4-digit prime permutation sequence and its 12-digit concatenation."
        self.header(
            49,
            "Find the second 4-digit prime permutation sequence and its 12-digit concatenation."
        )
        def task():
            for first in range(1111, 3340):
                second = first + 3330
                third = first + 6660
                
                # Skip the sequence given in the problem statement
                if first == 1487:
                    continue
                    
                # Check if all three numbers are prime
                if self.is_prime(first) and self.is_prime(second) and self.is_prime(third):
                    # Check if all three numbers are permutations of each other
                    if sorted(str(first)) == sorted(str(second)) == sorted(str(third)):
                        return f"{first}{second}{third}"
        result = self.run_task(
            "Finding the 4-digit prime permutation sequence...",
            task
        )
        print(f"The 12-digit concatenation of second 4-digit prime permutation sequence is: {Fore.GREEN}{result}{Fore.RESET} ")

    def problem50(self):
        "Finds the prime below the limit that is the sum of the most consecutive primes."
        self.header(
            50,
            "Finds the prime below the limit that is the sum of the most consecutive primes."
        )
        def task(limit:int):
            is_prime = self.sieve_of_eratosthenes_list(limit)
            primes = [i for i, p in enumerate(is_prime) if p]
            prefix_sums = [0]
            for p in primes:
                prefix_sums.append(prefix_sums[-1] + p)
                
            max_length = 0
            best_prime = 0
            n_primes = len(primes)
            for i in range(n_primes):
                for j in range(i + max_length + 1, n_primes):
                    window_sum = prefix_sums[j] - prefix_sums[i]
                    if window_sum >= limit:
                        break
                    if is_prime[window_sum]:
                        max_length = j - i
                        best_prime = window_sum
            return best_prime
        result = self.run_task(
            "Combing through the Sieve of Eratosthenes...",
            task,
            1_000_000
        )
        print(f"The prime below the limit that is the sum of the most consecutive primes is: {Fore.GREEN}{result}{Fore.RESET}")

