"""
Project Euler solutions: problem51 through problem75.

Problems51To75 is combined into EulerSolver in solver.py. It
genuinely inherits from UtilsMixin and EasterEggs since these problems
call self.header, self.run_task, self.is_prime, self.evaluate_hand, and
so on.
"""

import math
import itertools
import collections

from colorama import Fore

from .utils import UtilsMixin
from .easter_eggs import EasterEggs


class Problems51To75(UtilsMixin, EasterEggs):
    """Problem solutions 51-75."""

    def problem51(self):
        "Find the smallest prime that is part of an eight-prime-value family generated by replacing identical digit positions."
        self.header(
            51,
            "Find the smallest prime that is part of an eight-prime-value family generated by replacing identical digit positions."
        )
        def task():
            limit = 1000000
            is_prime = self.sieve_of_eratosthenes_list(limit)
            for p in range(100000, limit):
                if not is_prime[p]:
                    continue
                s_p = str(p)
                digits_to_check = set(s_p[:-1]) 
                for d in digits_to_check:
                    indices = [i for i, char in enumerate(s_p) if char == d]
                    for r in range(1, len(indices) + 1):
                        for combo in itertools.combinations(indices, r):
                            family_size = 0
                            primes_in_family = []
                            for repl in range(10):
                                # Prevent leading zeros
                                if 0 in combo and repl == 0:
                                    continue
                                lst = list(s_p)
                                for idx in combo:
                                    lst[idx] = str(repl)
                                num = int("".join(lst))
                                if is_prime[num]:
                                    family_size += 1
                                    primes_in_family.append(num)
                            if family_size >= 8:
                                return primes_in_family
        result = self.run_task(
            "Finding the prime in the sieve...",
            task
        )
        print(f"The primes that is part of that family is: {Fore.GREEN}{result}{Fore.RESET}")
        print(f"With the smallest being: {Fore.GREEN}{result[0]}{Fore.RESET}")

    def problem52(self):
        "Find the smallest integer x where x, 2x, 3x, 4x, 5x, and 6x share digits."
        self.header(
            52,
            "Find the smallest integer x where x, 2x, 3x, 4x, 5x, and 6x share digits."
        )
        def task():
            for i in itertools.count(1):
                base_digits = sorted(str(i))
                # Check if 2*i through 6*i have the exact same sorted digits
                if all(sorted(str(j * i)) == base_digits for j in range(2, 7)):
                    return i
        result =self.run_task(
            "Finding the integer...",
            task
        )
        print(f"The smallest integer where they all share digits is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem53(self):
        "Find the number of combinatoric selections (n choose r) greater than one million for 1 <= n <= 100."
        self.header(
            53,
            "Find the number of combinatoric selections (n choose r) greater than one million for 1 <= n <= 100."
        )
        def task():
            count = 0
            for n in range(1, 101):
                for r in range(0, n + 1):
                    if math.comb(n, r) > 1_000_000:
                        count += 1
            return count
        result = self.run_task(
            "Finding the number...",
            task
        )
        print(f"The number of combinatoric selections greater than one million for 1 <= n <= 100 is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem54(self):
        "Find out how many poker hands Player 1 wins out of 1000 random matches against Player 2."
        self.header(
            54,
            "Find out how many poker hands Player 1 wins out of 1000 random matches against Player 2."
        )
        def task():
            p1_wins = 0
            with open("0054_poker.txt", "r") as f:
                lines = f.read().strip().split('\n')
                for line in lines:
                    cards = line.split()
                    if len(cards) != 10:
                        continue
                    player1_hand = cards[:5]
                    player2_hand = cards[5:]
                    if self.evaluate_hand(player1_hand) > self.evaluate_hand(player2_hand):
                        p1_wins += 1
            return p1_wins
        result = self.run_task(
            "Combing through the file and evaluating hands...",
            task
        )
        print(f"The number of poker hands Player 1 wins out of 1000 random matches against Player 2 is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem55(self):
        "Find out how many numbers from 0 to 9999 are Lychrel numbers"
        self.header(
            55,
            "Find out how many numbers from 0 to 9999 are Lychrel numbers"
        )
        def task():
            lychrel_count = sum(1 for i in range(10000) if self.is_lychrel(i))
            return lychrel_count
        result = self.run_task(
            "Finding all Lychrel numbers below 10000...",
            task
        )
        print(f"The number of Lychrel numbers from 0 to 9999 is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem56(self):
        "Find the maximum digital sum of a^b for natural numbers a, b < 100"
        self.header(
            56,
            "Find the maximum digital sum of a^b for natural numbers a, b < 100"
        )
        def task():
            return max(sum(int(c) for c in str(a**b)) for a in range(100) for b in range(100))
        result = self.run_task(
            "Finding the maximum power...",
            task
        )
        print(f"The maximum digital sum of a^b for natural numbers is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem57(self):
        "Find out how many of the first 1000 square root of 2 expansions have a longer numerator than denominator."
        self.header(
            57,
            "Find out how many of the first 1000 square root of 2 expansions have a longer numerator than denominator."
        )
        def task():
            limit = 1000
            count = 0
            p, q = 3, 2
            for _ in range(2, limit + 1):
                p, q = p + 2 * q, p + q
                if len(str(p)) > len(str(q)):
                    count += 1
            first_p, first_q = 3, 2
            initial_count = 1 if len(str(first_p)) > len(str(first_q)) else 0
            return count + initial_count
        result = self.run_task(
            "Looking through square root expansions...",
            task
        )
        print(f"The number of the first 1000 square root of 2 expansions is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem58(self):
        "Find out the side length of the square spiral for which the ratio of primes along both diagonals first falls below 10%"
        self.header(
            58,
            "Find out the side length of the square spiral for which the ratio of primes along both diagonals first falls below 10%"
        )
        def task():
            prime_count = 0
            side_length = 1
            current_val = 1
            while True:
                side_length += 2
                step = side_length - 1
                for _ in range(4):
                    current_val += step
                    if self.is_prime(current_val):
                        prime_count += 1
                total_diagonal_elements = 2 * side_length - 1
                if prime_count * 10 < total_diagonal_elements:
                    return side_length
        result = self.run_task(
            "Looking through spirals...",
            task
        )
        print(f"The side length of the square spiral is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem59(self):
        "Decrypt the message by brute-forcing a repeating three-letter XOR key and return the sum of its ASCII values."
        self.header(
            59,
            "Decrypt the message by brute-forcing a repeating three-letter XOR key and return the sum of its ASCII values."
        )
        with open("0059_cipher.txt", "r") as f:
            cipher = f.read()
        def brute_force(cipher_text_str):
            ciphertext = [int(x) for x in cipher_text_str.strip().split(',')]
            best_score = -1
            best_plaintext = []
            lowercase_ascii = range(97, 123)
            for key in itertools.product(lowercase_ascii, repeat=3):
                decrypted_chars = []
                space_count = 0
                is_valid_text = True
                for i, cipher_byte in enumerate(ciphertext):
                    plain_byte = cipher_byte ^ key[i % 3]
                    if plain_byte < 32 or plain_byte > 126:
                        is_valid_text = False
                        break
                    if plain_byte == 32: # ASCII for space ' '
                        space_count += 1
                    decrypted_chars.append(plain_byte)
                if is_valid_text and space_count > best_score:
                    best_score = space_count
                    best_plaintext = decrypted_chars
            readable_text = "".join(chr(b) for b in best_plaintext)
            preview = f"Decrypted Message Preview: {Fore.CYAN}{readable_text[:(self.terminal_width-40)]}...{Fore.RESET}"
            return sum(best_plaintext), preview, readable_text
        result, text_preview, full_text = self.run_task(
            "Brute forcing attempts...",
            brute_force,
            cipher
        )
        print(f"Sum of ASCII values decrypted: {Fore.GREEN}{result}{Fore.RESET}")
        print(text_preview)
        filename = self.save_output(59, "decrypted", full_text)
        print(f"Saved decrypted message to {Fore.GREEN}{filename}{Fore.RESET}")

    def problem60(self):
        "Find the lowest sum for a set of five primes for which any two primes concatenate to produce another prime."
        self.header(
            60,
            "Find the lowest sum for a set of five primes for which any two primes concatenate to produce another prime."
        )
        pair_cache = {}
        IS_PRIME_LOOKUP = self.sieve_of_eratosthenes_list(30000)

        def check_pair(p1, p2):
            """Returns True if both concatenations of p1 and p2 are prime."""
            key = (p1, p2) if p1 < p2 else (p2, p1)
            if key in pair_cache:
                return pair_cache[key]
            
            c1 = int(f"{p1}{p2}")
            c2 = int(f"{p2}{p1}")
            
            result = self.is_prime(c1) and self.is_prime(c2)
            pair_cache[key] = result
            return result

        def solve():
            base_primes = [i for i in range(3, 10000) if IS_PRIME_LOOKUP[i] and i != 5]
            partners = {}
            for i, p1 in enumerate(base_primes):
                partners[p1] = []
                for p2 in base_primes[i + 1:]:
                    if check_pair(p1, p2):
                        partners[p1].append(p2)
            for p1 in base_primes:
                for p2 in partners[p1]:
                    p3_candidates = [p for p in partners[p2] if p in partners[p1]]
                    for p3 in p3_candidates:
                        p4_candidates = [p for p in partners[p3] if p in p3_candidates]
                        for p4 in p4_candidates:
                            p5_candidates = [p for p in partners[p4] if p in p4_candidates]
                            for p5 in p5_candidates:
                                subset = [p1, p2, p3, p4, p5]
                                return subset, sum(subset)
        prime_set, lowest_sum = self.run_task(
            "Combing through prime sets...",
            solve
        )
        print(f"The lowest sum for a set of five primes is: {Fore.GREEN}{lowest_sum}{Fore.RESET}")
        print(f"With the set being: {Fore.GREEN}{prime_set}{Fore.RESET}")

    def problem61(self):
        "Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type."
        self.header(
            61,
            "Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type."
        )
        def task():
            poly_map = self.generate_polygonal_numbers()
            def dfs(current_num, remaining_types, current_cycle):
                if not remaining_types:
                    # Check if the cycle closes back to the very first number
                    if current_num % 100 == current_cycle[0] // 100:
                        return sum(current_cycle)
                    return None
                suffix = current_num % 100
                for next_type in list(remaining_types):
                    for candidate in poly_map[next_type]:
                        if candidate // 100 == suffix:
                            remaining_types.remove(next_type)
                            current_cycle.append(candidate)
                            
                            result = dfs(candidate, remaining_types, current_cycle)
                            if result:
                                return result
                            current_cycle.pop()
                            remaining_types.add(next_type)
                return None
            # Kick off DFS from every available 4-digit Octagonal number
            for start_num in poly_map[8]:
                initial_types = {3, 4, 5, 6, 7}
                result = dfs(start_num, initial_types, [start_num])
                if result:
                    return result
        result = self.run_task(
            "Finding all cyclic 4-digit numbers...",
            task
        )
        print(f"The sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem62(self):
        "Find the smallest cube for which exactly five permutations of its digits are cube."
        self.header(
            62,
            "Find the smallest cube for which exactly five permutations of its digits are cube."
        )
        def task():
            # Store sorted digit fingerprints as keys and a list of their cubes as values
            cube_tracker = collections.defaultdict(list)
            root = 1
            while True:
                cube = root ** 3
                fingerprint = ''.join(sorted(str(cube)))
                cube_tracker[fingerprint].append(cube)
                if len(cube_tracker[fingerprint]) == 5:
                    return cube_tracker[fingerprint][0]
                root += 1
        result = self.run_task(
            "Finding all cube permutations...",
            task
        )
        print(f"The smallest cube for which exactly five permutations of its digits are cube is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem63(self):
        "Find the number of n-digit positive integers exist which are also an nth power."
        self.header(
            63,
            "Find the number of n-digit positive integers exist which are also an nth power."
        )
        def task():
            total = 0
            for b in range(1, 10):
                for e in range(1, 22):
                    if len(str(b ** e)) == e:
                        total += 1
            return total
        result = self.run_task(
            "Looking through powers...",
            task
        )
        print(f"The number of n-digit positive integers exist which are also an nth power is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem64(self):
        "Find the number of odd-period continued fractions for square roots up to 10000."
        self.header(
            64,
            "Find the number of odd-period continued fractions for square roots up to 10000."
        )
        def task():
            odd_period_count = sum(1 for i in range(1, 10001) if self.get_period_length(i) % 2 == 1)
            return odd_period_count
        result = self.run_task(
            "Iterating through periods...",
            task
        )
        print(f"The number of odd-period continued fractions for square roots up to 10000 is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem65(self):
        "Find the sum of digits in the numerator of the 100th convergent of the continued fraction for e."
        self.header(
            65,
            "Find the sum of digits in the numerator of the 100th convergent of the continued fraction for e."
        )
        def task():
            terms = [2]
            k = 1
            while len(terms) < 100:
                terms.extend([1, 2 * k, 1])
                k += 1
            terms = terms[:100]
            
            numerator = 1
            denominator = terms.pop() 
            for term in reversed(terms):
                denominator, numerator = term * denominator + numerator, denominator
            final_numerator = denominator
            
            return sum(int(digit) for digit in str(final_numerator))
        result = self.run_task(
            "Looking through Euler's Number...",
            task
        )
        print(f"The sum of digits in the numerator of the 100th convergent of the continued fraction for e is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem66(self):
        "Find the value of D ≤ 1000 for which Pell's equation x^2 - Dy^2 = 1 yields the largest minimal solution in x."
        self.header(
            66,
            "Find the value of D ≤ 1000 for which Pell's equation x^2 - Dy^2 = 1 yields the largest minimal solution in x."
        )
        def task():
            max_x = 0
            result_d = 0
            for d in range(2, 1001):
                if not self.is_square(d):
                    x = self.solve_pell(d)
                    if x > max_x:
                        max_x = x
                        result_d = d
            return result_d
        result = self.run_task(
            "Trying Pell's equation...",
            task
        )
        print(f"The value of D for which Pell's equation gives the largest minimal solution is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem67(self):
        "Find the maximum total from top to bottom in a triangle with one-hundred rows."
        self.header(
            67,
            "Find the maximum total from top to bottom in a triangle with one-hundred rows."
        )
        def task():
            with open("0067_triangle.txt", "r") as f:
                triangle = [[int(num) for num in line.split()] for line in f]
            for row in range(len(triangle) - 2, -1, -1):
                for col in range(len(triangle[row])):
                    max_child = max(triangle[row + 1][col], triangle[row + 1][col + 1])
                    triangle[row][col] += max_child

            return triangle[0][0]
        result = self.run_task(
            "Combing through all possibilities...",
            task
        )
        print(f"The maximum total from top to bottom in a triangle with one-hundred rows is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem68(self):
        "Find out the maximum 16-digit string for a \"magic\" 5-gon ring."
        self.header(
            68,
            "Find out the maximum 16-digit string for a \"magic\" 5-gon ring."
        )
        def solve_magic_5gon():
            nums = list(range(1, 11))
            max_string = ""
            
            # Generate all permutations of 10 numbers
            # For optimisation, we only evaluate configurations where 10 is an outer node
            for p in itertools.permutations(nums):
                x0, x1, x2, x3, x4 = p[0], p[1], p[2], p[3], p[4]
                y0, y1, y2, y3, y4 = p[5], p[6], p[7], p[8], p[9]
                if 10 in (y0, y1, y2, y3, y4):
                    continue
                if x0 > min(x1, x2, x3, x4):
                    continue
                line1 = x0 + y0 + y1
                line2 = x1 + y1 + y2
                line3 = x2 + y2 + y3
                line4 = x3 + y3 + y4
                line5 = x4 + y4 + y0
                
                if line1 == line2 == line3 == line4 == line5:
                    candidate_str = (
                        f"{x0}{y0}{y1}"
                        f"{x1}{y1}{y2}"
                        f"{x2}{y2}{y3}"
                        f"{x3}{y3}{y4}"
                        f"{x4}{y4}{y0}"
                    )
                    if candidate_str > max_string:
                        max_string = candidate_str
                        
            return max_string
        result = self.run_task(
            "Working out \"magic\" 5-gon rings...",
            solve_magic_5gon
        )
        print(f"The maximum 16-digit string for a \"magic\" 5-gon ring is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem69(self):
        "Find the value of n ≤ 1,000,000 for which the ratio n/φ(n) is maximised."
        self.header(
            69,
            "Find the value of n ≤ 1,000,000 for which the ratio n/φ(n) is maximised."
        )
        def task(limit=1_000_000):
            # Initialize phi array where φ[i] = i
            φ = list(range(limit + 1))
            for i in range(2, limit + 1):
                if φ[i] == i:  # i is a prime number
                    for j in range(i, limit + 1, i):
                        φ[j] -= φ[j] // i  # Apply the formula factor (1 - 1/p)
            max_ratio = 0
            best_n = 0
            for n in range(2, limit + 1):
                ratio = n / φ[n]
                if ratio > max_ratio:
                    max_ratio = ratio
                    best_n = n
                    
            return best_n
        result = self.run_task(
            "φ...",
            task
        )
        print(f"The value of n ≤ 1,000,000 for which the ratio n/φ(n) is maximised is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem70(self):
        "Find the value of n < 10^7 for which φ(n) is a permutation of n and the ratio n/φ(n) is minimised."
        self.header(
            70,
            "Find the value of n < 10^7 for which φ(n) is a permutation of n and the ratio n/φ(n) is minimised."
        )
        def task():
            limit = 10_000_000
            is_prime = self.sieve_of_eratosthenes_list(limit)
            primes = [i for i, prime in enumerate(is_prime) if prime]
            min_ratio = float('inf')
            best_n = 0
            
            for i in range(len(primes)):
                p1 = primes[i]
                if p1 * p1 >= limit:
                    break
                for j in range(i, len(primes)):
                    p2 = primes[j]
                    n = p1 * p2
                    if n >= limit:
                        break
                        
                    phi = (p1 - 1) * (p2 - 1)
                    if sorted(str(n)) == sorted(str(phi)):
                        ratio = n / phi
                        if ratio < min_ratio:
                            min_ratio = ratio
                            best_n = n
                            
            return best_n
        result = self.run_task(
            "Inspecting through primes...",
            task
        )
        print(f"The value of n for which φ(n) is a permutation of n and the ratio n/φ(n) is minimised is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem71(self):
        "Find the numerator of the fraction immediately to the left of 3/7, by listing the set of reduced proper fractions for d ≤ 1,000,000 in ascending order of size."
        self.header(
            71,
            "Find the numerator of the fraction immediately to the left of 3/7, by listing the set of reduced proper fractions for d ≤ 1,000,000 in ascending order of size."
        )
        def task(max_d:int = 1_000_000):
            best_n, best_d = 0, 1
            target_n, target_d = 3, 7
            
            for d in range(1, max_d + 1):
                # Find the largest numerator n such that n/d < 3/7
                n = (target_n * d - 1) // target_d
                
                if n * best_d > best_n * d:
                    best_n, best_d = n, d
                    
            return best_n
        result = self.run_task(
            "Reducing proper fractions...",
            task
        )
        print(f"The numerator of the fraction immediately to the left of 3/7 is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem72(self):
        "Find the number of elements in the set of reduced proper fractions n/d for d ≤ 1,000,000"
        self.header(
            72,
            "Find the number of elements in the set of reduced proper fractions n/d for d ≤ 1,000,000"
        )
        def task(limit:int=1_000_000):
            # Initialize phi array where phi[i] initially equals i
            φ = list(range(limit + 1))
            
            for i in range(2, limit + 1):
                if φ[i] == i:  # i is prime
                    for j in range(i, limit + 1, i):
                        φ[j] -= φ[j] // i
                        
            # Sum all totients from d = 2 to limit
            return sum(φ[2:])
        result = self.run_task(
            "Looking through the set...",
            task
        )
        print(f"The number of elements in the set of reduced proper fractions n/d is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem73(self):
        "Find how many reduced proper fractions lie strictly between 1/3 and 1/2 for denominators d ≤ 12,000."
        self.header(
            73,
            "Find how many reduced proper fractions lie strictly between 1/3 and 1/2 for denominators d ≤ 12,000."
        )
        def task(limit:int=12_000):
            count = 0
            stack = [(1, 3, 1, 2)]
            while stack:
                n1, d1, n2, d2 = stack.pop()
                nm, dm = n1 + n2, d1 + d2
                if dm <= limit:
                    count += 1
                    # Push both halves to the stack to explore further
                    stack.append((n1, d1, nm, dm))
                    stack.append((nm, dm, n2, d2))
                    
            return count
        result = self.run_task(
            "Reducing proper fractions... ",
            task
        )
        print(f"The number of reduced proper fractions lie strictly between 1/3 and 1/2 is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem74(self):
        "Find the number of chains with a starting number below one million that contain exactly 60 non-repeating terms"
        self.header(
            74,
            "Find the number of chains with a starting number below one million that contain exactly 60 non-repeating terms"
        )
        # Precompute factorials for digits 0 through 9
        FACTORIAL = [math.factorial(i) for i in range(10)]

        def next_number(n):
            total = 0
            while n > 0:
                total += FACTORIAL[n % 10]
                n //= 10
            return total

        def get_chain_length(n, cache):
            original_n = n
            seen = []
            while n not in cache:
                if n in seen:
                    break
                seen.append(n)
                n = next_number(n)
            
            # Calculate length for the visited sequence
            length = cache.get(n, 0)
            for i in reversed(seen):
                length += 1
                cache[i] = length
            return cache[original_n]

        def solve():
            cache = {}
            limit = 1000000
            count = 0
            for i in range(limit):
                if get_chain_length(i, cache) == 60:
                    count += 1
            return count
        result = self.run_task(
            "Iterating Factorials...",
            solve
        )
        print(f"The number of chains with a starting number below one million is: {Fore.GREEN}{result}{Fore.RESET}")

    def problem75(self):
        "Find the number of wire lengths up to 1,500,000 that can be bent into a right-angled triangle in exactly one way."
        self.header(
            75,
            "Find the number of wire lengths up to 1,500,000 that can be bent into a right-angled triangle in exactly one way."
        )
        def primitive_perimeter_generator(limit):
            """Generates the perimeter of unique primitive Pythagorean triples."""
            # The perimeter formula is P = s * (s + t)
            # Since t > 0, s^2 is always less than the limit
            max_s = math.isqrt(limit) + 1
            for s in range(3, max_s, 2):
                for t in range(s - 2, 0, -2):
                    if math.gcd(s, t) == 1:
                        perimeter = s * (s + t)
                        if perimeter <= limit:
                            yield perimeter

        def solve():
            LIMIT = 1500000
            perimeter_counts = [0] * (LIMIT + 1)
            
            # Consume perimeters from the generator
            for prim_p in primitive_perimeter_generator(LIMIT):
                for multiple_p in range(prim_p, LIMIT + 1, prim_p):
                    perimeter_counts[multiple_p] += 1
            return perimeter_counts.count(1)
        result = self.run_task(
            "Combing through Pythagorean Triples...",
            solve
        )
        print(f"The number of wire lengths that can be bent into a right-angled triangle in exactly one way is: {Fore.GREEN}{result}{Fore.RESET}")

